language: node_js
node_js:
- '10'
script:
- npm install
- npm run build
after_script:
- sed -i "s/GH_TOKEN/${GH_TOKEN}/g" ./_config.yml
- if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy; fi
notifications:
  email: false
